runtime: python38

handlers:
- url: /static
  static_dir: static/

- url: /templates
  static_dir: templates/

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  script: app.app

- url: /.*
  script: auto
