runtime: python38

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /templates
  static_dir: templates/

- url: /static
  static_dir: static/

- url: /.*
  script: auto
